### ISSUE TITLE
When will the OFFLINE use case become GA?

### ISSUE THREAD

**Issue by nebula0248** [stolostron/acm-hive-openshift-releases#38]
My customer is hoping to use RHACM to deploy air-gapped OCP clusters using an air-gapped RHACM. Seems I can change the ClusterImageSet object's spec.releaseImage to point to a mirrored registry for offline purpose. However, this GitHub README is saying the feature is still in TECH PREVIEW. May I know if that has been GA? Or when? Thanks.

**Comment by ldpliu** [comment]
Actually, it's already GA, and we have changed the doc about this.
